### ISSUE TITLE
Use switch expressions

### ISSUE THREAD

**Issue by ANF-Studios** [Juptian/Compiler#2]
In [Binder.cs](https://github.com/Juptian/Compiler/blob/main/Source/Compiler/CodeAnalysis/Binding/Binder.cs) and in [Syntax Facts.cs](https://github.com/Juptian/Compiler/blob/main/Source/Compiler/CodeAnalysis/Syntax/SyntaxFacts.cs), switch expressions should be used instead as they are super useful and came in C# 9. This project does use .NET Core 5 so it is a good idea.

**Comment by Juptian** [comment]
They already do anf :|

**Comment by ANF-Studios** [comment]
> Feel free to make a PR to fix them! But from what I can see, they already do!

If I had to make a PR, you didn't need to close it! Oh well.. I guess you don't want them.

**Comment by Juptian** [comment]
> > Feel free to make a PR to fix them! But from what I can see, they already do!
> 
> If I had to make a PR, you didn't need to close it! Oh well.. I guess you don't want them.

No please do feel free to make a pr, I merely closed it because I figured there was nothing else to say

**Comment by ANF-Studios** [comment]
Perfect!
